services:
  db:
    image: mysql:latest
    container_name: doce-encontro-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DCEN_DB_PASS}
      MYSQL_DATABASE: ${DCEN_DB}
    ports:
      - ${DB_PORT}:${DOCKER_PORT}
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: doce-encontro-backend
    restart: on-failure
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:${DOCKER_PORT}/${DCEN_DB}
      SPRING_DATASOURCE_USERNAME: ${DCEN_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DCEN_DB_PASS}
      DCEN_EMAIL: ${DCEN_EMAIL}
      DCEN_EMAIL_PASS: ${DCEN_EMAIL_PASS}
      DCEN_PASS: ${DCEN_PASS}
      HOST: ${FRONTEND_HOST}
      DOCKER_PORT: ${DOCKER_PORT}
      DB_PORT: ${DB_PORT}
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

volumes:
  db_data: null
